algoritmo "exercicio 8"
// Função :
// Autor :
// Data : 16/11/2022
// Seção de Declarações 
var
largura:real
altura:real
area:real
tinta:real

inicio
escreva("Quantos metros de largura possui a parede?" )
leia(largura)
escreva("Quantos metros de altura possui a parede?" )
leia(altura)
area <- largura * altura
tinta <- area / 2

escreval("A parede possui ",area," M² e é necessario ",tinta," litros de tinta para pinta-la")



fimalgoritmo
